# Generated by Django 3.2.5 on 2021-11-17 16:43

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20211117_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='application_status',
            field=models.CharField(choices=[(clubs.models.Membership.UserTypes['NON_MEMBER'], 1), (clubs.models.Membership.UserTypes['MEMBER'], 2), (clubs.models.Membership.UserTypes['OFFICER'], 3)], default=clubs.models.Membership.Application['PENDING'], max_length=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='user_type',
            field=models.CharField(choices=[(clubs.models.Membership.Application['PENDING'], 1), (clubs.models.Membership.Application['APPROVED'], 2), (clubs.models.Membership.Application['DENIED'], 3)], default=clubs.models.Membership.UserTypes['NON_MEMBER'], max_length=10),
        ),
    ]
