# Generated by Django 3.2.5 on 2021-11-17 17:48

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20211117_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='application_status',
            field=models.CharField(choices=[(clubs.models.Membership.UserTypes['NON_MEMBER'], 1), (clubs.models.Membership.UserTypes['MEMBER'], 2), (clubs.models.Membership.UserTypes['OFFICER'], 3), (clubs.models.Membership.UserTypes['OWNER'], 4)], default=clubs.models.Membership.Application['PENDING'], max_length=10),
        ),
    ]
