# Generated by Django 3.2.5 on 2021-11-22 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_membership_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Club name must consist of at least three alphanumericals', regex='^\\w{3,}$')]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='application_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_type',
            field=models.CharField(choices=[('NM', 'Non Member'), ('MB', 'Member'), ('OF', 'Officer'), ('OW', 'Owner')], default='NM', max_length=10),
        ),
    ]
