# Generated by Django 3.2.5 on 2021-11-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='personal_statement',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
