# Generated by Django 3.2.5 on 2021-11-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_membership_personal_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='personal_statement',
            field=models.CharField(max_length=500),
        ),
    ]
