# Generated by Django 3.2.5 on 2021-11-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_membership_personal_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='club',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
