# Generated by Django 3.2.5 on 2021-11-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_auto_20211125_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='club',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
