# Generated by Django 3.2.5 on 2021-11-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_alter_tournament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
