# Generated by Django 3.2.5 on 2021-12-04 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0030_alter_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Club name must start with a letter and contain only letters, number, and spaces.', regex='^[a-zA-Z][a-zA-Z0-9 ]+')]),
        ),
    ]
