# Generated by Django 3.2.5 on 2021-12-07 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_alter_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='coorganizers',
            field=models.ManyToManyField(related_name='coorganizers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
