# Generated by Django 3.2.5 on 2021-12-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_tournamentparticipation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentparticipation',
            unique_together={('user', 'tournament')},
        ),
    ]
