# Generated by Django 3.2.5 on 2021-12-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_auto_20211208_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='stage',
            field=models.CharField(choices=[('E', 'Elimination'), ('G', 'Group Stages')], default='E', max_length=1),
        ),
    ]
