# Generated by Django 3.2.5 on 2021-12-09 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_auto_20211209_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='clubs.group'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('E', 'Elimination'), ('G', 'Group Stage')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='stage',
            field=models.CharField(choices=[('S', 'Signups Open'), ('C', 'Signups Closed'), ('E', 'Elimination'), ('G', 'Group Stages'), ('F', 'Finished')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='tournamentparticipation',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='clubs.tournament'),
        ),
    ]
