# Generated by Django 3.2.5 on 2021-12-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_auto_20211207_1449'),
        ('clubs', '0037_auto_20211209_0146'),
    ]

    operations = [
    ]
