# Generated by Django 3.2.5 on 2021-12-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_auto_20211209_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
