# Generated by Django 3.2.5 on 2021-12-09 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0038_merge_0032_auto_20211207_1449_0037_auto_20211209_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='coorganizers',
            field=models.ManyToManyField(blank=True, related_name='coorganizers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
