# Generated by Django 3.2.5 on 2021-12-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0038_auto_20211209_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='group', max_length=100),
            preserve_default=False,
        ),
    ]
