# Generated by Django 3.2.5 on 2021-12-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0038_auto_20211209_1636'),
        ('clubs', '0039_auto_20211209_1620'),
    ]

    operations = [
    ]
