# Generated by Django 3.2.5 on 2021-12-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0039_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='elimination_stage',
            field=models.IntegerField(null=True),
        ),
    ]
