# Generated by Django 3.2.5 on 2021-12-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_group_elimination_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='elimination_stage',
        ),
        migrations.RemoveField(
            model_name='match',
            name='stage',
        ),
        migrations.AddField(
            model_name='group',
            name='phase',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='stage',
            field=models.CharField(choices=[('E', 'Elimination'), ('G', 'Group Stage')], default='E', max_length=1),
        ),
    ]
