# Generated by Django 3.2.5 on 2021-12-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_merge_0038_auto_20211209_1636_0039_auto_20211209_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('name', 'club'), name='unique_tournament_club'),
        ),
    ]
