# Generated by Django 3.2.5 on 2021-12-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_merge_0038_auto_20211209_1636_0039_auto_20211209_1620'),
        ('clubs', '0041_auto_20211210_1505'),
    ]

    operations = [
    ]
