# Generated by Django 3.2.5 on 2021-12-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0041_auto_20211213_1003'),
        ('clubs', '0042_merge_20211212_1707'),
    ]

    operations = [
    ]
