# Generated by Django 3.2.5 on 2021-12-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0045_auto_20211214_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='highest_elo_rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='membership',
            name='lowest_elo_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
