# Generated by Django 3.2.5 on 2021-12-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0043_merge_20211216_1705'),
        ('clubs', '0046_auto_20211214_2301'),
    ]

    operations = [
    ]
